# Generated by Django 4.2.9 on 2024-02-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_file', models.FileField(blank=True, null=True, upload_to='text_files')),
                ('filename', models.CharField(blank=True, max_length=124, null=True)),
                ('audiofile', models.FileField(blank=True, null=True, upload_to='audio_files')),
                ('zipfile', models.FileField(blank=True, null=True, upload_to='zip_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=124, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
