# Generated by Django 4.2.9 on 2024-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='text_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
