# Generated by Django 4.2.9 on 2024-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_filename',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='filename',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
