# Generated by Django 4.2.9 on 2024-02-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0003_audiofile_audio_filename_audiofile_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio_file',
            new_name='audiofile',
        ),
    ]
